import '@/src/app/[lang]/globals.css';
import '../../config/i18n-config';

import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import { ReactNode } from 'react';

import LanguageSync from '@/src/shared/LanguageSync';

import { getSession, getUsername } from '../../actions/auth';
import I18nProvider from '../../config/I18nProvider';
import Header from '../../features/header/Header';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
});

type Props = {
  children: ReactNode;
  params: Promise<{ lang: string }>;
};

export const metadata: Metadata = {
  title: 'CODELANG',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: Props) {
  const userId = await getSession();
  const username = await getUsername();

  const { lang } = await params;

  return (
    <html lang={lang}>
      <body className={playfairDisplay.className}>
        <I18nProvider>
          <LanguageSync lang={lang} />
          <Header username={username} user={userId} />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
