import './globals.css';
import '../../config/i18n-config';

import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import { ReactNode } from 'react';

import LanguageSync from '@/src/shared/LanguageSync';

import { getSession } from '../../actions/auth';
import I18nProvider from '../../config/I18nProvider';
import Header from '../../features/header/Header';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CODELANG',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: { lang: string };
}>) {
  const user = await getSession();

  const { lang } = await params;

  return (
    <html lang={lang}>
      <body className={playfairDisplay.className}>
        <I18nProvider>
          <LanguageSync lang={lang} />
          <Header user={user} />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
