import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import { FaCode } from 'react-icons/fa';
import { IoLanguageSharp } from 'react-icons/io5';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-dvh h-16 flex justify-between items-center">
          <div>
            <button type="button">
              <FaCode />
            </button>
            <h2>Codelang</h2>
          </div>
          <div>
            <button>Sign in</button>
            <div>
              <IoLanguageSharp />
              <h2>EN</h2>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
