import './globals.css';
import '../utils/i18n';

import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import { ReactNode } from 'react';

import { getSession } from '../actions/auth';
import Header from '../features/header/Header';
import I18nProvider from '../shared/providers/I18nProvider';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CODELANG',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const user = await getSession();

  return (
    <html lang="en">
      <body className={playfairDisplay.className}>
        <I18nProvider>
          <Header user={user} />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
