import './globals.css';

import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import { ReactNode } from 'react';

import { getSession } from '../actions/auth';
import Header from '../components/Header';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CODELANG',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const user = await getSession();

  return (
    <html lang="en">
      <body className={playfairDisplay.className}>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
